name: CI with Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Set PYTHONPATH
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          echo "PYTHONPATH configurado como: ${GITHUB_WORKSPACE}"



      # Run tests with coverage
      - name: Run tests
        run: |
          pytest --cov=MyAdventures --cov-report=xml MyAdventures/tests/

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: 647224db-a0b9-4694-8265-90a976f6fc7e
          files: ./coverage.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
